### ISSUE TITLE
更换数据集

### ISSUE THREAD

**Issue by QuokkaD** [taishan1994/pytorch_casrel_triple_extraction#1]
请问想更换别的数据集的话，必须要和train_data.json里面的格式完全一样吗？是否可以直接将webNLG这样的数据集放入代码中？

**Comment by taishan1994** [comment]
> 请问想更换别的数据集的话，必须要和train_data.json里面的格式完全一样吗？是否可以直接将webNLG这样的数据集放入代码中？

不一定，保证data_loader.py里面能够正确加载数据就行，具体情况可自己修改。

**Comment by QuokkaD** [comment]
谢谢博主，之前的问题已经解决！还想再问一下中文和英文的训练差别很大吗，是否可以更换预训练模型解决呢？

**Comment by taishan1994** [comment]
> 谢谢博主，之前的问题已经解决！还想再问一下中文和英文的训练差别很大吗，是否可以更换预训练模型解决呢？

主要差别是英文单词可能会被拆分为子词，因此数据处理的时候要注意重新将索引进行调整。然后就是要换一个英文预训练模型。

**Comment by QuokkaD** [comment]
> > 谢谢博主，之前的问题已经解决！还想再问一下中文和英文的训练差别很大吗，是否可以更换预训练模型解决呢？
> 
> 主要差别是英文单词可能会被拆分为子词，因此数据处理的时候要注意重新将索引进行调整。然后就是要换一个英文预训练模型。

索引调整是指dataloader里面要进行修改吗

**Comment by taishan1994** [comment]
> > > 谢谢博主，之前的问题已经解决！还想再问一下中文和英文的训练差别很大吗，是否可以更换预训练模型解决呢？
> > 
> > 
> > 主要差别是英文单词可能会被拆分为子词，因此数据处理的时候要注意重新将索引进行调整。然后就是要换一个英文预训练模型。
> 
> 索引调整是指dataloader里面要进行修改吗

是的。

**Comment by rengar011** [comment]
请问训练集是怎么标注的？

**Comment by taishan1994** [comment]
> 请问训练集是怎么标注的？

用的标准数据集，自带标注，你也可以使用doccano标注，然后转换成相关的格式。
